<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LaptopCommerce.Wishlist.Domain\LaptopCommerce.Wishlist.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\LaptopCommerce.Application.Abstractions\LaptopCommerce.Application.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
