<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LaptopCommerce.Analytics.Application\LaptopCommerce.Analytics.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\LaptopCommerce.Infrastructure.Shared\LaptopCommerce.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
